#!/bin/sh

remote_name="$1"
remote_url="$2"

case "$remote_name:$remote_url" in
  origin:*Sonarr/Sonarr.git|origin:*Sonarr/Sonarr|*:https://github.com/Sonarr/Sonarr.git|*:https://github.com/Sonarr/Sonarr)
    echo "Push blocked: public Sonarr remote is disabled for this checkout." >&2
    exit 1
    ;;
esac

exit 0
