// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'field': string;
  'fieldGrid': string;
  'fullWidth': string;
  'modalBody': string;
  'modalFooter': string;
  'notes': string;
  'warningList': string;
}
export const cssExports: CssExports;
export default cssExports;
